@startuml

class App{
+ getPromiseHistoryClient() : PromiseHistoryClient
}

class PromiseHistoryClient {
- getPromiseHistoryByOrderIdActivity : GetPromiseHistoryByOrderIdActivity

+ getPromiseHistoryByOrderId(orderId : String) : PromiseHistory
}

class GetPromiseHistoryByOrderIdActivity {
- orderDao : ReadOnlyDao <String, Order>
- promiseDao : ReadOnlyDao <String, List<Promise>>

+ getPromiseHistoryByOrderId(orderId : String) : PromiseHistory
}

class OrderDao {
- omaClient : OrderManipulationAuthorityClient

+ get(orderId : String) : Order
- convertToOrderItem(orderResultItem : OrderResultItem) : OrderItem
}

class PromiseDao {
- dpsClient : DeliveryPromiseServiceClient
- omaClient : OrderManipulationAuthorityClient

+ get (customerOrderItemId : String) : List<Promise>
}

interface ReadOnlyDao {
+ get()
}

class OrderManipulationAuthorityClient {
- omaService : OrderManipulationAuthority

+ getCustomerOrderByOrderId(orderId : String) : OrderResult
+ getCustomerOrderItemByOrderItemId(orderItemId : String) : OrderResultItem
}

class DeliveryPromiseServiceClient {
- dpService : DeliveryPromiseService

+ getDeliveryPromiseByOrderItemId(customerOrderItemId : String) : Promise
}

App -|> PromiseHistoryClient
PromiseHistoryClient *-- GetPromiseHistoryByOrderIdActivity

GetPromiseHistoryByOrderIdActivity o-- OrderDao
GetPromiseHistoryByOrderIdActivity o-- PromiseDao
OrderDao .|> ReadOnlyDao
ReadOnlyDao <|. PromiseDao
DeliveryPromiseServiceClient --o PromiseDao
PromiseDao o-- OrderManipulationAuthorityClient
OrderDao o-- OrderManipulationAuthorityClient


@enduml